SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `agenda` DEFAULT CHARACTER SET utf8 ;
USE `agenda` ;

-- -----------------------------------------------------
-- Table `agenda`.`amigo`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `agenda`.`amigo` (
  `idamigo` INT(11) NOT NULL AUTO_INCREMENT ,
  `nombre` CHAR(45) NULL DEFAULT NULL ,
  `direccion` CHAR(45) NULL DEFAULT NULL ,
  `telefono` CHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`idamigo`) )
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

USE `agenda` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
